version: '3'

services:
  photos:
    build: .
    depends_on:
      - 'database'
    ports: 
      - '3030:3004' 
    environment:
      - PG_HOST=database
      - PG_USER=postgres
      - PG_DATA=ot
      

  database:
    image: postgres:latest
    ports:
      - '5432:5432'