version: 2
jobs:
  build:
    machine:
      - image: circleci/node:6.13.1
      - image: circleci/mysql:5.7
      environment:
          MYSQL_HOST: 127.0.0.1
          MYSQL_DB: cava_table
          MYSQL_USER: root
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_PASSWORD:

    working_directory: ~/vincent-photos

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm test
